import { subMoveDict } from "@/common/moves";
import { getIntroductions } from "../services/user-data";
import { findUserByEmail } from "../services/user-service";
import { createSentenceFeedbackUseCase } from "../use-cases/createSentenceFeedbackUseCase";

export const seedFeedbacks = async () => {
  const choosenUser = await findUserByEmail("assoulsidali@gmail.com");
  if (!choosenUser) {
    console.error("Please Seed Choosen User First.");
    return;
  }
  let page = 1;
  let total: number = Infinity;
  while (page <= total) {
    const introductions = await getIntroductions(
      choosenUser.id,
      { page },
      "User",
    );
    total = introductions.total_pages;

    console.log(
      `Processing page ${page} of ${total} ------------------------------------ `,
    );

    if (introductions.total_pages === 0) {
      console.error("Please Seed Introductions First.");
      return;
    }
    for (const introduction of introductions.data) {
      for (const sentence of introduction.sentences) {
        if (sentence.feedback) {
          console.log(
            `Sentence already processed ${sentence.id} introduction ${introduction.id}`,
          );
          continue;
        }
        const liked = Math.random() > 0.5;
        console.log(
          `Creating Sentence feedback for introduction ${introduction.id} sentence ${sentence.id}`,
        );
        await createSentenceFeedbackUseCase(
          {
            introductionId: introduction.id,
            sentenceId: sentence.id,
            sentenceText: sentence.text,
            move: sentence.move,
            subMove: sentence.subMove,
            feedback: {
              correctMove: !liked ? (sentence.move + 1) % 3 : undefined,
              correctSubMove: !liked ? 0 : undefined,
              reason:
                "This is a feedback reason which is automaticly generated by a seeding process.",
              username: choosenUser.name,
              image: choosenUser.image,
              liked,
            },
          },
          choosenUser.id,
          {
            username: choosenUser.name,
            userRole: choosenUser.role,
            image: choosenUser.image,
          },
        );
        console.log(`Feedback created for sentence ${sentence.id}`);
      }
    }
    page++;
  }
};
